// 教材数据文件（由 scripts/convert_textbook.mjs 自动生成，请勿手改）
module.exports = {
  subjects: [
    {
      name: '英语',
      open: true,
      order: 1,
    },
  ],
  trees: {
    英语: {
      learningPaths: [
        {
          name: '词汇',
          open: true,
          order: 1,
          textbooks: [
            {
              name: '人教版 PEP',
              order: 1,
              semesters: [
                {
                  name: '七年级上册',
                  order: 1,
                  chapters: [
                    {
                      title: 'Starter Unit 1 Hello!',
                      order: 1,
                      knowledge: [
                        {
                          word: 'hello',
                          meaning: '你好',
                          order: 1,
                          ipa: 'həˈləʊ',
                          partOfSpeech: 'int.',
                          example: 'Hello, everyone!',
                          translation: '大家好！',
                        },
                        {
                          word: 'hi',
                          meaning: '嗨',
                          order: 2,
                          ipa: 'haɪ',
                          partOfSpeech: 'int.',
                          example: 'Hi, Li Ming!',
                          translation: '嗨，李明！',
                        },
                        {
                          word: 'good',
                          meaning: '好的',
                          order: 3,
                          ipa: 'ɡʊd',
                          partOfSpeech: 'adj.',
                          example: 'Good morning, teacher.',
                          translation: '老师，早上好。',
                        },
                        {
                          word: 'morning',
                          meaning: '早晨；上午',
                          order: 4,
                          ipa: 'ˈmɔːnɪŋ',
                          partOfSpeech: 'n.',
                          example: 'Good morning!',
                          translation: '早上好！',
                        },
                        {
                          word: 'class',
                          meaning: '班级；同学们',
                          order: 5,
                          ipa: 'klɑːs',
                          partOfSpeech: 'n.',
                          example: 'Good morning, class.',
                          translation: '同学们，早上好。',
                        },
                        {
                          word: 'my',
                          meaning: '我的',
                          order: 6,
                          ipa: 'maɪ',
                          partOfSpeech: 'pron.',
                          example: 'My name is Anna.',
                          translation: '我的名字叫安娜。',
                        },
                        {
                          word: 'name',
                          meaning: '名字',
                          order: 7,
                          ipa: 'neɪm',
                          partOfSpeech: 'n.',
                          example: 'What is your name?',
                          translation: '你叫什么名字？',
                        },
                        {
                          word: 'is',
                          meaning: '是（be 动词第三人称单数）',
                          order: 8,
                          ipa: 'ɪz',
                          partOfSpeech: 'v.',
                          example: 'She is my friend.',
                          translation: '她是我的朋友。',
                        },
                        {
                          word: 'am',
                          meaning: '是（用于 I）',
                          order: 9,
                          ipa: 'æm',
                          partOfSpeech: 'v.',
                          example: 'I am a student.',
                          translation: '我是一名学生。',
                        },
                        {
                          word: 'are',
                          meaning: '是（用于 you/we/they）',
                          order: 10,
                          ipa: 'ɑː(r)',
                          partOfSpeech: 'v.',
                          example: 'You are my friend.',
                          translation: '你是我的朋友。',
                        },
                        {
                          word: 'you',
                          meaning: '你；你们',
                          order: 11,
                          ipa: 'juː',
                          partOfSpeech: 'pron.',
                          example: 'Nice to meet you.',
                          translation: '见到你很高兴。',
                        },
                        {
                          word: 'your',
                          meaning: '你的；你们的',
                          order: 12,
                          ipa: 'jɔː(r)',
                          partOfSpeech: 'pron.',
                          example: 'Is this your book?',
                          translation: '这是你的书吗？',
                        },
                        {
                          word: 'I',
                          meaning: '我',
                          order: 13,
                          ipa: 'aɪ',
                          partOfSpeech: 'pron.',
                          example: 'I am Li Hua.',
                          translation: '我是李华。',
                        },
                        {
                          word: 'nice',
                          meaning: '令人愉快的',
                          order: 14,
                          ipa: 'naɪs',
                          partOfSpeech: 'adj.',
                          example: 'Nice to meet you.',
                          translation: '见到你很高兴。',
                        },
                        {
                          word: 'meet',
                          meaning: '遇见；结识',
                          order: 15,
                          ipa: 'miːt',
                          partOfSpeech: 'v.',
                          example: 'Nice to meet you, too.',
                          translation: '见到你也很高兴。',
                        },
                        {
                          word: 'too',
                          meaning: '也',
                          order: 16,
                          ipa: 'tuː',
                          partOfSpeech: 'adv.',
                          example: 'Nice to meet you, too.',
                          translation: '见到你也很高兴。',
                        },
                        {
                          word: 'goodbye',
                          meaning: '再见',
                          order: 17,
                          ipa: 'ˌɡʊdˈbaɪ',
                          partOfSpeech: 'int.',
                          example: 'Goodbye, my friend.',
                          translation: '再见，我的朋友。',
                        },
                        {
                          word: 'thank',
                          meaning: '感谢',
                          order: 18,
                          ipa: 'θæŋk',
                          partOfSpeech: 'v.',
                          example: 'Thank you very much.',
                          translation: '非常感谢你。',
                        },
                      ],
                    },
                    {
                      title: 'Starter Unit 2 Keep Tidy!',
                      order: 2,
                      knowledge: [
                        {
                          word: 'keep',
                          meaning: '保持',
                          order: 1,
                          ipa: 'kiːp',
                          partOfSpeech: 'v.',
                          example: 'Please keep your room tidy.',
                          translation: '请保持房间整洁。',
                        },
                        {
                          word: 'tidy',
                          meaning: '整洁的',
                          order: 2,
                          ipa: 'ˈtaɪdi',
                          partOfSpeech: 'adj.',
                          example: 'My room is very tidy.',
                          translation: '我的房间很整洁。',
                        },
                        {
                          word: 'room',
                          meaning: '房间',
                          order: 3,
                          ipa: 'ruːm',
                          partOfSpeech: 'n.',
                          example: 'This is my room.',
                          translation: '这是我的房间。',
                        },
                        {
                          word: 'desk',
                          meaning: '书桌',
                          order: 4,
                          ipa: 'desk',
                          partOfSpeech: 'n.',
                          example: 'The desk is near the window.',
                          translation: '书桌在窗边。',
                        },
                        {
                          word: 'chair',
                          meaning: '椅子',
                          order: 5,
                          ipa: 'tʃeə(r)',
                          partOfSpeech: 'n.',
                          example: 'The chair is blue.',
                          translation: '椅子是蓝色的。',
                        },
                        {
                          word: 'book',
                          meaning: '书',
                          order: 6,
                          ipa: 'bʊk',
                          partOfSpeech: 'n.',
                          example: 'I have a new book.',
                          translation: '我有一本新书。',
                        },
                        {
                          word: 'pen',
                          meaning: '钢笔',
                          order: 7,
                          ipa: 'pen',
                          partOfSpeech: 'n.',
                          example: 'This pen is black.',
                          translation: '这支钢笔是黑色的。',
                        },
                        {
                          word: 'pencil',
                          meaning: '铅笔',
                          order: 8,
                          ipa: 'ˈpensl',
                          partOfSpeech: 'n.',
                          example: 'The pencil is on the desk.',
                          translation: '铅笔在书桌上。',
                        },
                        {
                          word: 'ruler',
                          meaning: '尺子',
                          order: 9,
                          ipa: 'ˈruːlə(r)',
                          partOfSpeech: 'n.',
                          example: 'My ruler is long.',
                          translation: '我的尺子很长。',
                        },
                        {
                          word: 'eraser',
                          meaning: '橡皮',
                          order: 10,
                          ipa: 'ɪˈreɪzə(r)',
                          partOfSpeech: 'n.',
                          example: 'I need an eraser.',
                          translation: '我需要一块橡皮。',
                        },
                        {
                          word: 'schoolbag',
                          meaning: '书包',
                          order: 11,
                          ipa: 'ˈskuːlbæɡ',
                          partOfSpeech: 'n.',
                          example: 'My schoolbag is heavy.',
                          translation: '我的书包很重。',
                        },
                        {
                          word: 'put',
                          meaning: '放；放置',
                          order: 12,
                          ipa: 'pʊt',
                          partOfSpeech: 'v.',
                          example: 'Put the book on the desk.',
                          translation: '把书放在书桌上。',
                        },
                        {
                          word: 'on',
                          meaning: '在……上',
                          order: 13,
                          ipa: 'ɒn',
                          partOfSpeech: 'prep.',
                          example: 'The pen is on the desk.',
                          translation: '钢笔在书桌上。',
                        },
                        {
                          word: 'in',
                          meaning: '在……里',
                          order: 14,
                          ipa: 'ɪn',
                          partOfSpeech: 'prep.',
                          example: 'The book is in the schoolbag.',
                          translation: '书在书包里。',
                        },
                        {
                          word: 'under',
                          meaning: '在……下面',
                          order: 15,
                          ipa: 'ˈʌndə(r)',
                          partOfSpeech: 'prep.',
                          example: 'The ruler is under the chair.',
                          translation: '尺子在椅子下面。',
                        },
                        {
                          word: 'clean',
                          meaning: '打扫；干净的',
                          order: 16,
                          ipa: 'kliːn',
                          partOfSpeech: 'v./adj.',
                          example: 'Clean your room, please.',
                          translation: '请打扫你的房间。',
                        },
                        {
                          word: 'please',
                          meaning: '请',
                          order: 17,
                          ipa: 'pliːz',
                          partOfSpeech: 'int.',
                          example: 'Sit down, please.',
                          translation: '请坐。',
                        },
                      ],
                    },
                    {
                      title: 'Starter Unit 3 Welcome!',
                      order: 3,
                      knowledge: [
                        {
                          word: 'welcome',
                          meaning: '欢迎',
                          order: 1,
                          ipa: 'ˈwelkəm',
                          partOfSpeech: 'v./int.',
                          example: 'Welcome to our school!',
                          translation: '欢迎来到我们学校！',
                        },
                        {
                          word: 'we',
                          meaning: '我们',
                          order: 2,
                          ipa: 'wiː',
                          partOfSpeech: 'pron.',
                          example: 'We are students.',
                          translation: '我们是学生。',
                        },
                        {
                          word: 'our',
                          meaning: '我们的',
                          order: 3,
                          ipa: 'ˈaʊə(r)',
                          partOfSpeech: 'pron.',
                          example: 'This is our classroom.',
                          translation: '这是我们的教室。',
                        },
                        {
                          word: 'school',
                          meaning: '学校',
                          order: 4,
                          ipa: 'skuːl',
                          partOfSpeech: 'n.',
                          example: 'Our school is big.',
                          translation: '我们的学校很大。',
                        },
                        {
                          word: 'new',
                          meaning: '新的',
                          order: 5,
                          ipa: 'njuː',
                          partOfSpeech: 'adj.',
                          example: 'I am a new student.',
                          translation: '我是一名新生。',
                        },
                        {
                          word: 'student',
                          meaning: '学生',
                          order: 6,
                          ipa: 'ˈstjuːdnt',
                          partOfSpeech: 'n.',
                          example: 'She is a good student.',
                          translation: '她是一名好学生。',
                        },
                        {
                          word: 'teacher',
                          meaning: '老师',
                          order: 7,
                          ipa: 'ˈtiːtʃə(r)',
                          partOfSpeech: 'n.',
                          example: 'My teacher is kind.',
                          translation: '我的老师很和蔼。',
                        },
                        {
                          word: 'grade',
                          meaning: '年级',
                          order: 8,
                          ipa: 'ɡreɪd',
                          partOfSpeech: 'n.',
                          example: 'I am in Grade Seven.',
                          translation: '我在七年级。',
                        },
                        {
                          word: 'seven',
                          meaning: '七',
                          order: 9,
                          ipa: 'ˈsevn',
                          partOfSpeech: 'num.',
                          example: 'I am in Class Two, Grade Seven.',
                          translation: '我在七年级二班。',
                        },
                        {
                          word: 'this',
                          meaning: '这；这个',
                          order: 10,
                          ipa: 'ðɪs',
                          partOfSpeech: 'pron.',
                          example: 'This is my school.',
                          translation: '这是我的学校。',
                        },
                        {
                          word: 'that',
                          meaning: '那；那个',
                          order: 11,
                          ipa: 'ðæt',
                          partOfSpeech: 'pron.',
                          example: 'That is my teacher.',
                          translation: '那是我的老师。',
                        },
                        {
                          word: 'see',
                          meaning: '看见',
                          order: 12,
                          ipa: 'siː',
                          partOfSpeech: 'v.',
                          example: 'I see a big playground.',
                          translation: '我看到一个大操场。',
                        },
                        {
                          word: 'look',
                          meaning: '看',
                          order: 13,
                          ipa: 'lʊk',
                          partOfSpeech: 'v.',
                          example: 'Look at the blackboard.',
                          translation: '看黑板。',
                        },
                        {
                          word: 'come',
                          meaning: '来',
                          order: 14,
                          ipa: 'kʌm',
                          partOfSpeech: 'v.',
                          example: 'Come to our school.',
                          translation: '来我们学校吧。',
                        },
                        {
                          word: 'playground',
                          meaning: '操场',
                          order: 15,
                          ipa: 'ˈpleɪɡraʊnd',
                          partOfSpeech: 'n.',
                          example: 'The playground is big.',
                          translation: '操场很大。',
                        },
                      ],
                    },
                    {
                      title: 'Unit 1 You and Me',
                      order: 4,
                      knowledge: [
                        {
                          word: 'me',
                          meaning: '我（宾格）',
                          order: 1,
                          ipa: 'miː',
                          partOfSpeech: 'pron.',
                          example: 'Please help me.',
                          translation: '请帮助我。',
                        },
                        {
                          word: 'he',
                          meaning: '他',
                          order: 2,
                          ipa: 'hiː',
                          partOfSpeech: 'pron.',
                          example: 'He is my classmate.',
                          translation: '他是我的同学。',
                        },
                        {
                          word: 'she',
                          meaning: '她',
                          order: 3,
                          ipa: 'ʃiː',
                          partOfSpeech: 'pron.',
                          example: 'She is my sister.',
                          translation: '她是我的妹妹。',
                        },
                        {
                          word: 'his',
                          meaning: '他的',
                          order: 4,
                          ipa: 'hɪz',
                          partOfSpeech: 'pron.',
                          example: 'His name is Tom.',
                          translation: '他的名字叫汤姆。',
                        },
                        {
                          word: 'her',
                          meaning: '她的',
                          order: 5,
                          ipa: 'hɜː(r)',
                          partOfSpeech: 'pron.',
                          example: 'Her bag is red.',
                          translation: '她的书包是红色的。',
                        },
                        {
                          word: 'friend',
                          meaning: '朋友',
                          order: 6,
                          ipa: 'frend',
                          partOfSpeech: 'n.',
                          example: 'She is my best friend.',
                          translation: '她是我最好的朋友。',
                        },
                        {
                          word: 'old',
                          meaning: '年老的；……岁的',
                          order: 7,
                          ipa: 'əʊld',
                          partOfSpeech: 'adj.',
                          example: 'How old are you?',
                          translation: '你几岁了？',
                        },
                        {
                          word: 'year',
                          meaning: '年；岁',
                          order: 8,
                          ipa: 'jɪə(r)',
                          partOfSpeech: 'n.',
                          example: 'I am twelve years old.',
                          translation: '我十二岁了。',
                        },
                        {
                          word: 'from',
                          meaning: '来自',
                          order: 9,
                          ipa: 'frɒm',
                          partOfSpeech: 'prep.',
                          example: 'I am from China.',
                          translation: '我来自中国。',
                        },
                        {
                          word: 'where',
                          meaning: '哪里',
                          order: 10,
                          ipa: 'weə(r)',
                          partOfSpeech: 'adv.',
                          example: 'Where are you from?',
                          translation: '你来自哪里？',
                        },
                        {
                          word: 'live',
                          meaning: '居住',
                          order: 11,
                          ipa: 'lɪv',
                          partOfSpeech: 'v.',
                          example: 'I live in Beijing.',
                          translation: '我住在北京。',
                        },
                        {
                          word: 'like',
                          meaning: '喜欢',
                          order: 12,
                          ipa: 'laɪk',
                          partOfSpeech: 'v.',
                          example: 'I like English very much.',
                          translation: '我非常喜欢英语。',
                        },
                        {
                          word: 'love',
                          meaning: '爱；热爱',
                          order: 13,
                          ipa: 'lʌv',
                          partOfSpeech: 'v.',
                          example: 'I love my school.',
                          translation: '我爱我的学校。',
                        },
                        {
                          word: 'sport',
                          meaning: '运动',
                          order: 14,
                          ipa: 'spɔːt',
                          partOfSpeech: 'n.',
                          example: 'My favourite sport is basketball.',
                          translation: '我最喜欢的运动是篮球。',
                        },
                        {
                          word: 'music',
                          meaning: '音乐',
                          order: 15,
                          ipa: 'ˈmjuːzɪk',
                          partOfSpeech: 'n.',
                          example: 'I like listening to music.',
                          translation: '我喜欢听音乐。',
                        },
                        {
                          word: 'play',
                          meaning: '玩；打（球）',
                          order: 16,
                          ipa: 'pleɪ',
                          partOfSpeech: 'v.',
                          example: 'I play basketball after school.',
                          translation: '我放学后打篮球。',
                        },
                        {
                          word: 'often',
                          meaning: '经常',
                          order: 17,
                          ipa: 'ˈɒfn',
                          partOfSpeech: 'adv.',
                          example: 'I often play sports.',
                          translation: '我经常做运动。',
                        },
                        {
                          word: 'favourite',
                          meaning: '最喜欢的',
                          order: 18,
                          ipa: 'ˈfeɪvərɪt',
                          partOfSpeech: 'adj.',
                          example: 'English is my favourite subject.',
                          translation: '英语是我最喜欢的科目。',
                        },
                      ],
                    },
                    {
                      title: "Unit 2 We're Family!",
                      order: 5,
                      knowledge: [
                        {
                          word: 'family',
                          meaning: '家庭',
                          order: 1,
                          ipa: 'ˈfæməli',
                          partOfSpeech: 'n.',
                          example: 'I love my family.',
                          translation: '我爱我的家。',
                        },
                        {
                          word: 'father',
                          meaning: '父亲',
                          order: 2,
                          ipa: 'ˈfɑːðə(r)',
                          partOfSpeech: 'n.',
                          example: 'My father is a doctor.',
                          translation: '我爸爸是一名医生。',
                        },
                        {
                          word: 'mother',
                          meaning: '母亲',
                          order: 3,
                          ipa: 'ˈmʌðə(r)',
                          partOfSpeech: 'n.',
                          example: 'My mother is a teacher.',
                          translation: '我妈妈是一名老师。',
                        },
                        {
                          word: 'parent',
                          meaning: '父（母）亲',
                          order: 4,
                          ipa: 'ˈpeərənt',
                          partOfSpeech: 'n.',
                          example: 'My parents are busy.',
                          translation: '我的父母很忙。',
                        },
                        {
                          word: 'brother',
                          meaning: '兄；弟',
                          order: 5,
                          ipa: 'ˈbrʌðə(r)',
                          partOfSpeech: 'n.',
                          example: 'My brother is tall.',
                          translation: '我哥哥很高。',
                        },
                        {
                          word: 'sister',
                          meaning: '姐；妹',
                          order: 6,
                          ipa: 'ˈsɪstə(r)',
                          partOfSpeech: 'n.',
                          example: 'My sister likes reading.',
                          translation: '我妹妹喜欢阅读。',
                        },
                        {
                          word: 'grandfather',
                          meaning: '祖父；外祖父',
                          order: 7,
                          ipa: 'ˈɡrænfɑːðə(r)',
                          partOfSpeech: 'n.',
                          example: 'My grandfather is seventy.',
                          translation: '我爷爷七十岁了。',
                        },
                        {
                          word: 'grandmother',
                          meaning: '祖母；外祖母',
                          order: 8,
                          ipa: 'ˈɡrænmʌðə(r)',
                          partOfSpeech: 'n.',
                          example: 'My grandmother lives with us.',
                          translation: '我奶奶和我们住。',
                        },
                        {
                          word: 'uncle',
                          meaning: '叔；伯；舅',
                          order: 9,
                          ipa: 'ˈʌŋkl',
                          partOfSpeech: 'n.',
                          example: 'My uncle lives in Shanghai.',
                          translation: '我叔叔住在上海。',
                        },
                        {
                          word: 'aunt',
                          meaning: '姑；姨；婶',
                          order: 10,
                          ipa: 'ɑːnt',
                          partOfSpeech: 'n.',
                          example: 'My aunt is a nurse.',
                          translation: '我姑姑是一名护士。',
                        },
                        {
                          word: 'cousin',
                          meaning: '堂（表）兄弟姐妹',
                          order: 11,
                          ipa: 'ˈkʌzn',
                          partOfSpeech: 'n.',
                          example: 'My cousin and I are the same age.',
                          translation: '我和我表哥同岁。',
                        },
                        {
                          word: 'son',
                          meaning: '儿子',
                          order: 12,
                          ipa: 'sʌn',
                          partOfSpeech: 'n.',
                          example: 'He is their only son.',
                          translation: '他是他们唯一的儿子。',
                        },
                        {
                          word: 'daughter',
                          meaning: '女儿',
                          order: 13,
                          ipa: 'ˈdɔːtə(r)',
                          partOfSpeech: 'n.',
                          example: 'Her daughter is five.',
                          translation: '她女儿五岁了。',
                        },
                        {
                          word: 'husband',
                          meaning: '丈夫',
                          order: 14,
                          ipa: 'ˈhʌzbənd',
                          partOfSpeech: 'n.',
                          example: 'Her husband is a driver.',
                          translation: '她的丈夫是一名司机。',
                        },
                        {
                          word: 'wife',
                          meaning: '妻子',
                          order: 15,
                          ipa: 'waɪf',
                          partOfSpeech: 'n.',
                          example: 'His wife is a doctor.',
                          translation: '他的妻子是一名医生。',
                        },
                        {
                          word: 'photo',
                          meaning: '照片',
                          order: 16,
                          ipa: 'ˈfəʊtəʊ',
                          partOfSpeech: 'n.',
                          example: 'This is a photo of my family.',
                          translation: '这是我的一张全家福。',
                        },
                        {
                          word: 'together',
                          meaning: '一起',
                          order: 17,
                          ipa: 'təˈɡeðə(r)',
                          partOfSpeech: 'adv.',
                          example: 'We often eat dinner together.',
                          translation: '我们经常一起吃晚饭。',
                        },
                        {
                          word: 'happy',
                          meaning: '快乐的',
                          order: 18,
                          ipa: 'ˈhæpi',
                          partOfSpeech: 'adj.',
                          example: 'We are a happy family.',
                          translation: '我们是快乐的一家。',
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  },
};
