// 示例种子数据（Owner 授权 A1，2026-07-19）。
// ⚠️ SAMPLE：仅用于开发联调，上线前必须由真实教材数据替换。
// 本文件是种子数据的唯一来源（云函数部署包无法引用包外文件，故不放 cloud/database/seed/）。
// 结构：学科 → 学习路径 → 教材 → 册次 → 章节 → 知识点（嵌套即层级，§3）。
module.exports = {
  subjects: [
    { name: '英语', open: true, order: 1 },
    { name: '数学', open: false, order: 2 },
    { name: '语文', open: false, order: 3 },
    { name: '物理', open: false, order: 4 },
    { name: '化学', open: false, order: 5 },
    { name: '生物', open: false, order: 6 },
    { name: '历史', open: false, order: 7 },
    { name: '地理', open: false, order: 8 },
    { name: '政治', open: false, order: 9 },
  ],
  // 仅挂在「英语」下（§5：Vocabulary 开放，其余 Coming Soon）
  english: {
    learningPaths: [
      { name: 'Vocabulary', open: true, order: 1 },
      { name: 'Grammar', open: false, order: 2 },
    ],
    vocabulary: {
      textbooks: [{ name: '人教版 PEP', order: 1 }],
      semesters: [{ name: '七年级上册', order: 1 }],
      chapters: [
        {
          title: 'Unit 1',
          order: 1,
          knowledge: [
            {
              word: 'hello',
              ipa: 'həˈləʊ',
              meaning: '你好',
              partOfSpeech: 'int.',
              example: 'Hello, everyone!',
              translation: '大家好！',
              order: 1,
            },
            {
              word: 'name',
              ipa: 'neɪm',
              meaning: '名字',
              partOfSpeech: 'n.',
              example: 'My name is Li Ming.',
              translation: '我的名字叫李明。',
              order: 2,
            },
            {
              word: 'friend',
              ipa: 'frend',
              meaning: '朋友',
              partOfSpeech: 'n.',
              example: 'She is my best friend.',
              translation: '她是我最好的朋友。',
              order: 3,
            },
            {
              word: 'teacher',
              ipa: 'ˈtiːtʃə(r)',
              meaning: '老师',
              partOfSpeech: 'n.',
              example: 'Our teacher is kind.',
              translation: '我们的老师很和蔼。',
              order: 4,
            },
            {
              word: 'student',
              ipa: 'ˈstjuːdnt',
              meaning: '学生',
              partOfSpeech: 'n.',
              example: 'He is a good student.',
              translation: '他是一名好学生。',
              order: 5,
            },
            {
              word: 'school',
              ipa: 'skuːl',
              meaning: '学校',
              partOfSpeech: 'n.',
              example: 'I go to school by bus.',
              translation: '我乘公交车上学。',
              order: 6,
            },
            {
              word: 'book',
              ipa: 'bʊk',
              meaning: '书',
              partOfSpeech: 'n.',
              example: 'This book is interesting.',
              translation: '这本书很有趣。',
              order: 7,
            },
            {
              word: 'pen',
              ipa: 'pen',
              meaning: '钢笔',
              partOfSpeech: 'n.',
              example: 'I have a red pen.',
              translation: '我有一支红钢笔。',
              order: 8,
            },
            {
              word: 'bag',
              ipa: 'bæɡ',
              meaning: '书包',
              partOfSpeech: 'n.',
              example: 'My bag is heavy.',
              translation: '我的书包很重。',
              order: 9,
            },
            {
              word: 'desk',
              ipa: 'desk',
              meaning: '课桌',
              partOfSpeech: 'n.',
              example: 'The desk is clean.',
              translation: '课桌很干净。',
              order: 10,
            },
          ],
        },
        {
          title: 'Unit 2',
          order: 2,
          knowledge: [
            {
              word: 'family',
              ipa: 'ˈfæməli',
              meaning: '家庭',
              partOfSpeech: 'n.',
              example: 'I love my family.',
              translation: '我爱我的家。',
              order: 1,
            },
            {
              word: 'father',
              ipa: 'ˈfɑːðə(r)',
              meaning: '父亲',
              partOfSpeech: 'n.',
              example: 'My father is a doctor.',
              translation: '我爸爸是一名医生。',
              order: 2,
            },
            {
              word: 'mother',
              ipa: 'ˈmʌðə(r)',
              meaning: '母亲',
              partOfSpeech: 'n.',
              example: 'My mother cooks well.',
              translation: '我妈妈做饭很好吃。',
              order: 3,
            },
            {
              word: 'brother',
              ipa: 'ˈbrʌðə(r)',
              meaning: '兄弟',
              partOfSpeech: 'n.',
              example: 'My brother is tall.',
              translation: '我哥哥很高。',
              order: 4,
            },
            {
              word: 'sister',
              ipa: 'ˈsɪstə(r)',
              meaning: '姐妹',
              partOfSpeech: 'n.',
              example: 'My sister likes reading.',
              translation: '我妹妹喜欢阅读。',
              order: 5,
            },
            {
              word: 'grandfather',
              ipa: 'ˈɡrænfɑːðə(r)',
              meaning: '祖父',
              partOfSpeech: 'n.',
              example: 'My grandfather is seventy.',
              translation: '我爷爷七十岁了。',
              order: 6,
            },
            {
              word: 'grandmother',
              ipa: 'ˈɡrænmʌðə(r)',
              meaning: '祖母',
              partOfSpeech: 'n.',
              example: 'My grandmother lives with us.',
              translation: '我奶奶和我们住。',
              order: 7,
            },
            {
              word: 'parent',
              ipa: 'ˈpeərənt',
              meaning: '父（母）亲',
              partOfSpeech: 'n.',
              example: 'His parents are teachers.',
              translation: '他的父母都是老师。',
              order: 8,
            },
            {
              word: 'uncle',
              ipa: 'ˈʌŋkl',
              meaning: '叔叔',
              partOfSpeech: 'n.',
              example: 'My uncle lives in Beijing.',
              translation: '我叔叔住在北京。',
              order: 9,
            },
            {
              word: 'aunt',
              ipa: 'ɑːnt',
              meaning: '姑姑；阿姨',
              partOfSpeech: 'n.',
              example: 'My aunt is a nurse.',
              translation: '我姑姑是一名护士。',
              order: 10,
            },
          ],
        },
      ],
    },
  },
};
